// <auto-generated />
using Introduccion.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Introduccion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220530151837_AddImagenRuta")]
    partial class AddImagenRuta
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Introduccion.Models.Amigo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ciudad")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("imagenRuta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Amigos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ciudad = 12,
                            Correo = "paco@gmail.com",
                            Nombre = "Paco"
                        },
                        new
                        {
                            Id = 2,
                            Ciudad = 16,
                            Correo = "maira@gmail.com",
                            Nombre = "Maira"
                        },
                        new
                        {
                            Id = 3,
                            Ciudad = 17,
                            Correo = "maria@gmail.com",
                            Nombre = "Maria"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
